### ISSUE TITLE
Backup all project only 

### ISSUE THREAD

**Issue by chenoi** [redex557/gitlab-backup#1]
Hi...I just trying your script to backup. This script run must have group... i don't have group ... how can i run this script without group name/id? Please advise. Thank you

**Comment by redex557** [comment]
Hello,
this script was meant to backup GitLab groups, give me a few hours and I will update the script for personal projects. 
Should be a quick patch ;)

**Comment by chenoi** [comment]
Thanks, appreciate for your update...

**Comment by redex557** [comment]
Have a look at the latest version. The "-p" argument should do the thing you are looking for. 
Also found a bug with recursive groups while having a look at the script today :D

**Comment by chenoi** [comment]
Hi
I have re-test and it works great... I would like to run an auto set in
cron job. Thank you.

**Comment by redex557** [comment]
Yeah thats how I use it, just add the script to your crontab file...
