### ISSUE TITLE
How to get all the projects/groups backup onto single folder with timestamp foldername

### ISSUE THREAD

**Issue by chenoi** [redex557/gitlab-backup#2]
Hi sir, i would like to apply you script to backup my projects/groups..but the script does backup output into multiple project or groups folder. Im thinking to run daily cronjob. If possible the backup output of multiple folders can be consolidated onto single folder with datetime format as a folder name. Is it possible sir? Appreciate if you can help. Thank you

**Comment by redex557** [comment]
Hi,
did you try using the argument "-d" / "--directory" for this? 
Running backup.py -d /your/path/$(date "+%F_%X") should work like you want it ;)

**Comment by chenoi** [comment]
Noted...will test it and update later. Thanks
Updated: I'm getting error below
./backup.py -r -v -p -d /home/mylab/$(date "+%F_%X")
[2020-09-03 20:40:00] /home/mylab/2020-09-03_20:40:00 is not a valid directory

Appreciate your help. Thank you.

**Comment by chenoi** [comment]
Hi...still not able to get it works... same error not a valid directory....

**Comment by chenoi** [comment]
Hi sir,
Im getting the same error of  not a valid directory when run the script 
./backup.py -r -v -p -d /home/mylab/$(date "+%F_%X")

Appreciate if this enhancement can be done. Thank you

**Comment by redex557** [comment]
Oh, ok. I will have a look at this later tonight.
Should be a quick patch :)

**Comment by redex557** [comment]
made a quick patch, should work now

**Comment by chenoi** [comment]
Thank you sir, I will test it and confirm later.

**Comment by chenoi** [comment]
Hi sir, this is the error when run the script ...
./backup.py -r -v -p -d /home/mylab/$(date "+%F_%X")
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
[2020-09-08 07:48:49] Checking your arguments....
[2020-09-08 07:48:49] /home/mylab/2020-09-08_07:48:49 is not a existing directory, creating it now.
Traceback (most recent call last):
  File "./backup.py", line 148, in <module>
    check_args()
  File "./backup.py", line 65, in check_args
    os.makedirs(args.directory, exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
**I founded that im using python2.7... run python3 ok... If i got many groups meaning that i have multiple groupid, can this script cater the requirement? I can see got argument -g...but havent try it out...if multiple groupid, should i add for example -g groupid1,groupid2,groupid3,groupidx?**

**Comment by redex557** [comment]
Yes I'm running Python 3.8, but Python 3.7 should work fine. Python 2.7 is outdated ;)

For multiple groups just separate them with space like this: 
`./backup.py -r -v -p -d /home/mylab/$(date "+%F_%X") -g 1 2 3 4 5`

**Comment by redex557** [comment]
Also keep in mind that you don't need to add groups that are sub-groups of other groups. Those are found recursive.

**Comment by chenoi** [comment]
> Also keep in mind that you don't need to add groups that are sub-groups of other groups. Those are found recursive.

Meaning that just add parent group should be sufficient right...thanks

**Comment by chenoi** [comment]
> Yes I'm running Python 3.8, but Python 3.7 should work fine. Python 2.7 is outdated ;)
> 
> For multiple groups just separate them with space like this:
> `./backup.py -r -v -p -d /home/mylab/$(date "+%F_%X") -g 1 2 3 4 5`

Great...Noted and thank you
Can i add this line onto my cronjob? This is correct way right?

    * 3 * * * /usr/bin/python3  /home/mylab/./backup.py -r -v -p -d  /home/mylab/$(date "+%F_%X") -g 1 2 3 4 5 >> ~/cron.log 
    2>&1

**Comment by chenoi** [comment]
You deserved star from me... Im not a good python ...but I can say that...your script is simple, good to accomplish gitlab backup purposes. I will test it further and share my experiences or maybe any enhancement or bugs  found...

**Comment by redex557** [comment]
> > Yes I'm running Python 3.8, but Python 3.7 should work fine. Python 2.7 is outdated ;)
> > For multiple groups just separate them with space like this:
> > `./backup.py -r -v -p -d /home/mylab/$(date "+%F_%X") -g 1 2 3 4 5`
> 
> Great...Noted and thank you
> Can i add this line onto my cronjob? This is correct way right?
> 
> ```
> * 3 * * * /usr/bin/python3  /home/mylab/./backup.py -r -v -p -d  /home/mylab/$(date "+%F_%X") -g 1 2 3 4 5 >> ~/cron.log 
> 2>&1
> ```

/home/mylab/backup.py 
(without the dot) is the same thing but otherwise this looks good :+1:

**Comment by redex557** [comment]
> You deserved star from me... Im not a good python ...but I can say that...your script is simple, good to accomplish gitlab backup purposes. I will test it further and share my experiences or maybe any enhancement or bugs found...

Thanks! If you want to get better at python just start by automating small everyday tasks. That's how I came up with this tool.
Sure, just open a new issue for every bug or feature you would like.
