### ISSUE TITLE
Cannot run $(date "+%F_%X") in cronjob task

### ISSUE THREAD

**Issue by chenoi** [redex557/gitlab-backup#3]
Hi sir,
I face issue when run the script over cronjob

Issue:-
_*/5 * * * * /home/mylab/backup.py -r -v -p -d /home/mylab/$(date "+%F_%X") -g 11 21 33 >> /home/mylab/crontab.log 2>&1_
The script cannot run by the cronjob...seems cronjob did not read correctly line '$(date "+%F_%X")'. No file crontab.log created and no backup done. For testing further, I remove '$(date "+%F_%X")' and run as below

_*/5 * * * * /home/mylab/backup.py -r -v -p -d /home/mylab/ -g 11 21 33 >> /home/mylab/crontab.log 2>&1_
This time the script executed successfully by cronjob and created file crontab.log and backup done. I check crontab.log and files backup ok. But I'm not getting timestamp folder of each backup done (cannot add $(date "+%F_%X") into the cronjob line) ....  Appreciate if you can verify if this working on your side? Any way it can be done in cron job. Please assist thank you.

**Comment by chenoi** [comment]
Hi sir, I still not able to run the script in cronjob. Maybe I'm doing wrong, please advise and assist further. Appreciate your help. Thank you so much.

**Comment by redex557** [comment]
Could you please provide some more information on the error?
```cat /var/log/syslog | grep cron```

**Comment by redex557** [comment]
And give it a try like this: 
```*/5 * * * * /home/mylab/backup.py -r -v -p -d /home/mylab/$(date +\%F_\%X) -g 11 21 33 >> /home/mylab/crontab.log 2>&1```

**Comment by chenoi** [comment]
Hi sir,
I have run for testing and from my cron log , i received error message below, no backup created.
_usage: backup.py [-h] [-v] [-q] [-r] [-d DIRECTORY]
                    [-g GROUP_IDS [GROUP_IDS ...]] [-p] [-t]
backup.py: error: unrecognized arguments: PM

**Comment by redex557** [comment]
Seems to be your locale, have a look at 
`date +\%F_\%X`
vs.
`date +\%F_\%H:\%M:\%S`

**Comment by chenoi** [comment]
Do you mean that my locale should be change to comply ==> date +\%F_\%H:\%M:\%S 
my locale

LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

date +\%F_\%X
2020-09-15_04:17:49 PM

date +\%F_\%H:\%M:\%S
2020-09-15_16:17:58

**Comment by redex557** [comment]
No, just use `date +%F_%H:%M:%S` instead in your cron job  🙄

**Comment by redex557** [comment]
See the space in one of those date cmds...think about what that leads to....

**Comment by chenoi** [comment]
> No, just use `date +%F_%H:%M:%S` instead in your cron job 🙄

Hakkk.....yaa.... need to apply that...sorry... :-(
I noted that 24hrs format.... omg... my bad....

**Comment by chenoi** [comment]
Thank you so much for your help.... I'm learning new things today...
